# roles/grafana/tasks/main.yml

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    ports:
      - "3000:3000"
    restart_policy: always

- name: Wait for Grafana to be up
  uri:
    url: http://localhost:3000
    status_code: 200
    timeout: 30
  retries: 10
  delay: 10
  register: result
  until: result.status == 200

- name: Configure Prometheus as a data source
  grafana_datasource:
    name: Prometheus
    type: prometheus
    url: http://localhost:9090
    login_user: admin
    login_password: admin
    state: present
